POST http://127.0.0.1:8000/account/signup/ 
Content-Type: application/json

{ "first_name": "adam", "last_name": "ali", "email": "adnnnmam@mailnn.com", "password": "Pass1234!", "gender": "M"}

###

POST http://127.0.0.1:8000/account/login 
Content-Type: application/json

{ "email": "adnnnmam@mailnn.com", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json
Authorization: token xxx