# Generated by Django 5.0.4 on 2024-04-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('onCart', 'OnCart'), ('done', 'Done')], default='onCart', max_length=10),
        ),
    ]
