# Generated by Django 5.0.3 on 2024-04-01 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be at least 3 characters', regex='^.{4,}$')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be at least 3 characters', regex='^.{4,}$')])),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be at least 3 characters', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,16}$')])),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=6)),
            ],
        ),
    ]
