# Generated by Django 5.0.3 on 2024-04-04 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='nomatch', message='Name must contain only letters and be at least 3 characters long', regex='^[a-zA-Z]{3,}$')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='nomatch', message='Name must contain only letters and be at least 3 characters long', regex='^[a-zA-Z]{3,}$')])),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='nomatch', message='', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,16}$')])),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
