# Generated by Django 5.0.3 on 2024-04-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_status_orders_user_id'),
        ('user', '0002_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
