# Generated by Django 5.0.4 on 2024-04-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_address_alter_address_order_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
